version: '3.3'

services:
  redis:
    image: "redis:5.0.5-alpine"
    container_name: go-redis
  
  sample:
    build: .
    ports: 
      - "8080:8080"
    environment:
      - REDIS_HOST=redis:6379